from django import forms
from django.contrib.auth.models import User

class TestForm(forms.Form):
	'''Form to test the rendering of all fields types'''
	boolean = forms.BooleanField()
	char = forms.CharField(min_length=3, max_length=5)
	choice = forms.ChoiceField(choices=[('1', 'tomato'), ('2', 'apple')])
	typedchoice = forms.TypedChoiceField(choices=[('1', 'tomato'), ('2', 'apple')], coerce=int, empty_value = None)
	date = forms.DateField()
	datetime = forms.DateTimeField()
	decimal = forms.DecimalField(min_value=0, max_value=99, max_digits=5, decimal_places=3)
	duration = forms.DurationField()
	email = forms.EmailField(min_length=5, max_length=50)
	file = forms.FileField(max_length=100)
	filepath = forms.FilePathField(path='/tmp')
	float = forms.FloatField()
	image = forms.ImageField()
	integer = forms.IntegerField(min_value=0, max_value=100)
	genericipaddress = forms.GenericIPAddressField()
	multiplechoice = forms.MultipleChoiceField(choices=[('1', 'tomato'), ('2', 'apple')])
	typedmultiplechoice = forms.TypedMultipleChoiceField(choices=[('1', 'tomato'), ('2', 'apple')], coerce=int, empty_value = None)
	nullboolean = forms.NullBooleanField()
	regex = forms.RegexField(regex=r'\w+')
	slug = forms.SlugField()
	time = forms.TimeField()
	url = forms.URLField(min_length=3, max_length=100)
	uuid = forms.UUIDField()
	combo = forms.ComboField(fields=[forms.CharField(max_length=20), forms.EmailField()])
	splitdatetime = forms.SplitDateTimeField()
	modelchoice = forms.ModelChoiceField(queryset=User.objects.all())
	modelmultiplechoice = forms.ModelMultipleChoiceField(queryset=User.objects.all())
	
	required_boolean = forms.BooleanField(required=True)
	required_char = forms.CharField(required=True, min_length=3, max_length=5)
	required_choice = forms.ChoiceField(required=True, choices=[('1', 'tomato'), ('2', 'apple')])
	required_typedchoice = forms.TypedChoiceField(required=True, choices=[('1', 'tomato'), ('2', 'apple')], coerce=int, required_empty_value = None)
	required_date = forms.DateField(required=True)
	required_datetime = forms.DateTimeField(required=True)
	required_decimal = forms.DecimalField(required=True, min_value=0, max_value=99, max_digits=5, decimal_places=3)
	required_duration = forms.DurationField(required=True)
	required_email = forms.EmailField(required=True, min_length=5, max_length=50)
	required_file = forms.FileField(required=True, max_length=100)
	required_filepath = forms.FilePathField(required=True, path='/tmp')
	required_float = forms.FloatField(required=True)
	required_image = forms.ImageField(required=True)
	required_integer = forms.IntegerField(required=True, min_value=0, max_value=100)
	required_genericipaddress = forms.GenericIPAddressField(required=True)
	required_multiplechoice = forms.MultipleChoiceField(required=True, choices=[('1', 'tomato'), ('2', 'apple')])
	required_typedmultiplechoice = forms.TypedMultipleChoiceField(required=True, choices=[('1', 'tomato'), ('2', 'apple')], coerce=int, empty_value = None)
	required_nullboolean = forms.NullBooleanField(required=True)
	required_regex = forms.RegexField(required=True, regex=r'\w+')
	required_slug = forms.SlugField(required=True)
	required_time = forms.TimeField(required=True)
	required_url = forms.URLField(required=True, min_length=3, max_length=100)
	required_uuid = forms.UUIDField(required=True)
	required_combo = forms.ComboField(required=True, fields=[forms.CharField(max_length=20), forms.EmailField()])
	required_splitdatetime = forms.SplitDateTimeField(required=True)
	required_modelchoice = forms.ModelChoiceField(required=True, queryset=User.objects.all())
	required_modelmultiplechoice = forms.ModelMultipleChoiceField(required=True, queryset=User.objects.all())
	
	disabled_boolean = forms.BooleanField(disabled=True)
	disabled_char = forms.CharField(disabled=True, min_length=3, max_length=5)
	disabled_choice = forms.ChoiceField(disabled=True, choices=[('1', 'tomato'), ('2', 'apple')])
	disabled_typedchoice = forms.TypedChoiceField(disabled=True, choices=[('1', 'tomato'), ('2', 'apple')], coerce=int, disabled_empty_value = None)
	disabled_date = forms.DateField(disabled=True)
	disabled_datetime = forms.DateTimeField(disabled=True)
	disabled_decimal = forms.DecimalField(disabled=True, min_value=0, max_value=99, max_digits=5, decimal_places=3)
	disabled_duration = forms.DurationField(disabled=True)
	disabled_email = forms.EmailField(disabled=True, min_length=5, max_length=50)
	disabled_file = forms.FileField(disabled=True, max_length=100)
	disabled_filepath = forms.FilePathField(disabled=True, path='/tmp')
	disabled_float = forms.FloatField(disabled=True)
	disabled_image = forms.ImageField(disabled=True)
	disabled_integer = forms.IntegerField(disabled=True, min_value=0, max_value=100)
	disabled_genericipaddress = forms.GenericIPAddressField(disabled=True)
	disabled_multiplechoice = forms.MultipleChoiceField(disabled=True, choices=[('1', 'tomato'), ('2', 'apple')])
	disabled_typedmultiplechoice = forms.TypedMultipleChoiceField(disabled=True, choices=[('1', 'tomato'), ('2', 'apple')], coerce=int, empty_value = None)
	disabled_nullboolean = forms.NullBooleanField(disabled=True)
	disabled_regex = forms.RegexField(disabled=True, regex=r'\w+')
	disabled_slug = forms.SlugField(disabled=True)
	disabled_time = forms.TimeField(disabled=True)
	disabled_url = forms.URLField(disabled=True, min_length=3, max_length=100)
	disabled_uuid = forms.UUIDField(disabled=True)
	disabled_combo = forms.ComboField(disabled=True, fields=[forms.CharField(max_length=20), forms.EmailField()])
	disabled_splitdatetime = forms.SplitDateTimeField(disabled=True)
	disabled_modelchoice = forms.ModelChoiceField(disabled=True, queryset=User.objects.all())
	disabled_modelmultiplechoice = forms.ModelMultipleChoiceField(disabled=True, queryset=User.objects.all())
